### ISSUE TITLE
Search control fails silently on 429 (Too Many Requests)

### ISSUE THREAD

**Issue by MattiasSp** [origo-map/origo#1999]
**Description**
When making too many requests to a search endpoint (such as Origo Server after https://github.com/origo-map/origo-server/pull/108/commits/580f9b8a0d15d02e046581590893e1390b370278) the client can recieve a 429 - Too Many Requests - response. The search control does not give the user any useful feedback in these cases, failing silently instead.

**To Reproduce**
1. Make more than 100 requests to an Origo Server endpoint within the 15 minute window using the Search control.
2. See the client give no reaction at all, while logging the 429 error and `VM2401:1 Uncaught (in promise) SyntaxError: Unexpected token 'T', "Too many r"... is not valid JSON` to the console.

**Expected behavior**
A discrete visual feedback about the cause of the error, perhaps even with info about "try again in X seconds".

**Comment by MattiasSp** [comment]
If this is something that could/should be solved by a toaster message, would it make sense to make [the toaster function in infowindow_exporthandler.js](https://github.com/origo-map/origo/blob/master/src/infowindow_exporthandler.js#L212) into a more generalized utility function and reuse that?

**Comment by johnnyblasta** [comment]
The limit should be raised in origo-server, but that doesn't solve if the new limit is reached.

**Comment by MattiasSp** [comment]
I found the discussion in https://github.com/origo-map/origo/issues/1982 and could just add this issue as another occasion where a general purpose toaster would be useful :)
